In [1]:
import pandas as pd

In [2]:
#If warnings are imported and asked to be ignored, warning messages will not be shown after running the code

In [3]:
import warnings

In [4]:
warnings.filterwarnings("ignore")

In [5]:
dataset = pd.read_csv("insurance_pre.csv")

In [6]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [7]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [8]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [9]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [10]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [11]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [12]:
dependent = dataset[['charges']]

In [13]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=0.30, random_state=0)

In [16]:
x_train

      age     bmi  children  sex_male  smoker_yes
1163   18  28.215         0         0           0
196    39  32.800         0         0           0
438    52  46.750         5         0           0
183    44  26.410         0         0           0
1298   33  27.455         2         1           0
...   ...     ...       ...       ...         ...
763    27  26.030         0         1           0
835    42  35.970         2         1           0
1216   40  25.080         0         1           0
559    19  35.530         0         1           0
684    33  18.500         1         0           0

[936 rows x 5 columns]

In [17]:
x_test

      age     bmi  children  sex_male  smoker_yes
578    52  30.200         1         1           0
610    47  29.370         1         0           0
569    48  40.565         2         1           1
1034   61  38.380         0         1           0
198    51  18.050         0         0           0
...   ...     ...       ...       ...         ...
1261   28  37.100         1         1           0
494    21  25.700         4         1           1
97     55  38.280         0         1           0
418    64  39.160         1         1           0
920    62  25.000         0         0           0

[402 rows x 5 columns]

In [18]:
y_train

          charges
1163   2200.83085
196    5649.71500
438   12592.53450
183    7419.47790
1298   5261.46945
...           ...
763    3070.80870
835    7160.33030
1216   5415.66120
559    1646.42970
684    4766.02200

[936 rows x 1 columns]

In [19]:
y_test

          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [21]:
#Model creation in RandomForestRF

In [22]:
from sklearn.ensemble import RandomForestRegressor

In [23]:
#Importing GridsearchV for checking the model's performance with all the parameters and cross-validation

In [24]:
from sklearn.model_selection import GridSearchCV

In [25]:
#regressor=RandomForestRegressor(n_estimators=50, criterion='poisson', random_state=0)RF

In [26]:
#Assigning all the parameters to param_grid

In [27]:
param_grid = {'criterion':['squared_error','absolute_error', 'poisson'],
'max_features': ['sqrt','log2'],
'n_estimators':[10,100]}

In [28]:
#Passing all the parameters, RandomForesgRegressor to gridsearchcv to do gridsearch and cross validation. Refit=True, will get the best model

In [29]:
#If Refit=False, GridsearchCv will pull the last model and its parameters

In [30]:
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)

In [31]:
#regressor.fit(x_train,y_train)RF

In [32]:
#Grid.Fit method below creates the best model

In [33]:
grid.fit(x_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [34]:
#cv_results_ will have the result of Gridsearchcv

In [35]:
re=grid.cv_results_

In [36]:
#y_pred=regressor.predict(x_test)RF

In [37]:
#Evaluation Metrics

In [38]:
grid_predictions = grid.predict(x_test)

In [39]:
from sklearn.metrics import r2_score

In [40]:
r_score=r2_score(y_test,grid_predictions)

In [41]:
#r_score

In [42]:
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'poisson', 'max_features': 'sqrt', 'n_estimators': 100}: 0.8710020900260464

In [43]:
#Saving the best modelRF

In [44]:
#import pickleRF

In [45]:
#filename = "finalized_model_RandomForest.sav"RF

In [46]:
#pickle.dump(regressor, open(filename,'wb'))RF

In [47]:
#Assigning the results re to table for viewing the table

In [48]:
table=pd.DataFrame.from_dict(re)

In [49]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.041857,0.002584,0.004826,0.000949,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.835746,0.788813,0.790550,0.783403,0.753335,0.790369,0.026388,9
1,0.350711,0.008234,0.017484,0.002064,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.861204,0.786598,0.806893,0.825356,0.772227,0.810456,0.031115,5
2,0.034563,0.001064,0.003644,0.000312,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.848450,0.780174,0.800017,0.790504,0.763220,0.796473,0.028709,7
3,0.346686,0.006542,0.016445,0.001069,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.864143,0.790063,0.810973,0.825634,0.767934,0.811749,0.032645,3
4,0.092830,0.005930,0.003782,0.000407,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.845222,0.786152,0.790971,0.791623,0.732527,0.789299,0.035689,12
5,0.906660,0.012234,0.016949,0.002326,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.857122,0.792783,0.805689,0.820485,0.771084,0.809433,0.028838,6
6,0.090345,0.002874,0.003710,0.000451,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.837830,0.767051,0.800813,0.777752,0.765176,0.789725,0.027192,11
7,0.920404,0.012586,0.016085,0.000855,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.857103,0.795199,0.811319,0.829365,0.771000,0.812797,0.029313,2
8,0.040506,0.000551,0.003479,0.000262,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.830330,0.743998,0.795328,0.812758,0.767517,0.789986,0.030966,10
9,0.383739,0.007680,0.016157,0.000527,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.865982,0.789111,0.815120,0.827364,0.767086,0.812933,0.033754,1
10,0.039870,0.001722,0.003750,0.000397,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.840306,0.757045,0.799772,0.825672,0.755400,0.795639,0.034707,8
11,0.355436,0.034810,0.011329,0.001530,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.860488,0.785597,0.811528,0.826434,0.769457,0.810701,0.031806,4

In [50]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 56
BMI: 78
Children: 2
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1

In [52]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[46690.0696593]