In [1]:
import numpy as np

In [2]:
import warnings

In [3]:
warnings.filterwarnings("ignore")

In [4]:
import pandas as pd

In [5]:
dataset = pd.read_csv("insurance_pre.csv")

In [6]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [7]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [8]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [9]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [10]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [11]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [12]:
dependent = dataset[['charges']]

In [13]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [14]:
#from sklearn.model_selection import train_test_split

In [15]:
#x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=0.30, random_state=0)

In [16]:
#x_train

In [17]:
#x_test

In [18]:
#y_train

In [19]:
#y_test

In [20]:
#Model creation in RandomForestRF

In [21]:
from sklearn.ensemble import RandomForestRegressor

In [22]:
from sklearn.model_selection import GridSearchCV

In [23]:
param_grid = {'criterion':['squared_error','absolute_error','poisson'],
'max_features': ['auto','sqrt','log2'],
'n_estimators':[10,100]}

In [24]:
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)

In [25]:
grid.fit(independent, dependent)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [26]:
#regressor=RandomForestRegressor(n_estimators=50, criterion='poisson', random_state=0)RF

In [27]:
#regressor.fit(x_train,y_train)RF

In [28]:
#y_pred=regressor.predict(x_test)RF

In [29]:
#Evaluation MetricsRF

In [30]:
#from sklearn.metrics import r2_score

In [31]:
#r_score=r2_score(y_test,y_pred)RF

In [32]:
#r_scoreRF

In [33]:
#Saving the best modelRF

In [34]:
#import pickleRF

In [35]:
#filename = "finalized_model_RandomForest.sav"RF

In [36]:
#pickle.dump(regressor, open(filename,'wb'))RF

In [37]:
re=grid.cv_results_

In [38]:
grid_predictions = grid.predict(independent)

In [39]:
from sklearn.metrics import r2_score

In [40]:
r_score=r2_score(dependent,grid_predictions)

In [41]:
print("The R-Score value for best parameter {}:".format(grid.best_params_),r_score)

The R-Score value for best parameter {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100}: 0.9683569960253691

In [42]:
table = pd.DataFrame.from_dict(re)

In [43]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002416,0.000422,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
1,0.002707,0.000553,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
2,0.053163,0.002463,0.006206,0.000899,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.845065,0.777255,0.849335,0.799526,0.828767,0.819990,0.027612,8
3,0.386640,0.006789,0.019901,0.001776,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.858806,0.778050,0.860601,0.829325,0.843402,0.834037,0.030212,2
4,0.040335,0.000591,0.004879,0.000157,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.847825,0.735874,0.830644,0.811046,0.824226,0.809923,0.038872,12
5,0.387630,0.007473,0.019501,0.001221,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.853015,0.782090,0.858070,0.831947,0.841657,0.833356,0.027190,4
6,0.001549,0.000285,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
7,0.001580,0.000428,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
8,0.123754,0.006336,0.004646,0.000118,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.840785,0.766831,0.858266,0.812173,0.817089,0.819029,0.030946,9
9,1.257781,0.011723,0.017535,0.000971,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.855269,0.779135,0.852569,0.833075,0.844920,0.832993,0.028009,6
10,0.126591,0.002879,0.004784,0.000418,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.844043,0.756536,0.846841,0.811877,0.831165,0.818093,0.033162,10
11,1.238840,0.015929,0.016821,0.002582,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.856600,0.775856,0.863973,0.831718,0.844836,0.834597,0.031339,1
12,0.001672,0.000300,0.000000,0.000000,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.001380,0.000101,0.000000,0.000000,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
14,0.048462,0.000389,0.005437,0.000533,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.851310,0.765303,0.827889,0.818477,0.826655,0.817927,0.028494,11
15,0.431319,0.007622,0.018448,0.000470,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.857169,0.781900,0.863766,0.826984,0.839106,0.833785,0.029025,3
16,0.048547,0.003502,0.005843,0.001013,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.847001,0.767371,0.846474,0.816934,0.828702,0.821297,0.029245,7
17,0.437883,0.015106,0.017333,0.003858,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.857606,0.777673,0.861222,0.830918,0.837731,0.833030,0.029966,5

In [44]:
#age_input = float(input("Age= "))
#bmi_input = float(input("BMI= "))
#children_input = float(input("Children= "))
#sex_male_input = int(input("Male or Female 0 or 1: "))
#smoker_input = int(input("Smoker yes or no 0 or 1: "))

In [45]:
#Future_Predictions = grid.predict([[age_input, bmi_input, children_input, sex_male_input, smoker_input]])

In [46]:
#print("Future Predictions = {}".format(Future_Predictions))

In [47]:
import pickle

In [48]:
filename = "finalized_model_RFwtouttraintest.sav"

In [49]:
pickle.dump(grid, open(filename,'wb'))