In [3]:
import numpy as np

In [4]:
import warnings

In [5]:
warnings.filterwarnings("ignore")

In [6]:
import pandas as pd

In [7]:
dataset = pd.read_csv("insurance_pre.csv")

In [8]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [9]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [10]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [11]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [12]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [13]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [14]:
dependent = dataset[['charges']]

In [15]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [16]:
#from sklearn.model_selection import train_test_split

In [17]:
#x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=0.30, random_state=0)

In [18]:
#x_train

In [19]:
#x_test

In [20]:
#y_train

In [21]:
#y_test

In [22]:
#Model creation in RandomForestRF

In [23]:
from sklearn.ensemble import RandomForestRegressor

In [24]:
from sklearn.model_selection import GridSearchCV

In [25]:
param_grid = {'criterion':['squared_error','absolute_error','poisson'],
'max_features': ['auto','sqrt','log2'],
'n_estimators':[10,100]}

In [26]:
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)

In [27]:
grid.fit(independent, dependent)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [28]:
#regressor=RandomForestRegressor(n_estimators=50, criterion='poisson', random_state=0)RF

In [29]:
#regressor.fit(x_train,y_train)RF

In [30]:
#y_pred=regressor.predict(x_test)RF

In [33]:
#Evaluation MetricsRF

In [34]:
#from sklearn.metrics import r2_scoreRF

In [35]:
#r_score=r2_score(y_test,y_pred)RF

In [36]:
#r_scoreRF

In [37]:
#Saving the best modelRF

In [38]:
#import pickleRF

In [39]:
#filename = "finalized_model_RandomForest.sav"RF

In [40]:
#pickle.dump(regressor, open(filename,'wb'))RF

In [41]:
re=grid.cv_results_

In [45]:
print("The R-Score value for best parameter {}:".format(grid.best_params_))

The R-Score value for best parameter {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100}:

In [46]:
table = pd.DataFrame.from_dict(re)

In [47]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002410,0.000257,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
1,0.002845,0.000690,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
2,0.055473,0.002861,0.006126,0.001003,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.855585,0.759932,0.831793,0.809320,0.837204,0.818767,0.032912,11
3,0.453055,0.029393,0.019334,0.001614,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.857348,0.779266,0.863819,0.830800,0.840082,0.834263,0.029923,2
4,0.041248,0.001256,0.005678,0.000339,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.842938,0.773288,0.843111,0.815318,0.821514,0.819234,0.025548,9
5,0.394431,0.006824,0.019505,0.002202,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.857865,0.778066,0.857833,0.828570,0.841149,0.832696,0.029456,6
6,0.001531,0.000206,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
7,0.001801,0.000862,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
8,0.128700,0.005547,0.005441,0.000584,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.850876,0.762936,0.833276,0.818404,0.828662,0.818831,0.029855,10
9,1.276098,0.032634,0.018860,0.001632,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.857253,0.778701,0.857091,0.831504,0.845925,0.834095,0.029258,4
10,0.124663,0.003875,0.004388,0.000150,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.829816,0.756023,0.839370,0.822555,0.828012,0.815155,0.030060,12
11,1.255994,0.019257,0.016400,0.003641,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.857334,0.781684,0.861830,0.826519,0.850333,0.835540,0.029553,1
12,0.001272,0.000065,0.000000,0.000000,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.001441,0.000209,0.000000,0.000000,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
14,0.047491,0.000906,0.004940,0.000343,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.842398,0.773411,0.837168,0.813604,0.837655,0.820847,0.025753,7
15,0.436761,0.009501,0.018773,0.000893,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.859340,0.779607,0.860323,0.826967,0.842576,0.833763,0.029720,5
16,0.046844,0.002371,0.005971,0.001007,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.851484,0.774924,0.839182,0.811119,0.825923,0.820526,0.026471,8
17,0.440374,0.017538,0.018074,0.002623,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.855848,0.784384,0.860554,0.829060,0.841278,0.834225,0.027281,3

In [49]:
age_input = float(input("Age= "))
bmi_input = float(input("BMI= "))
children_input = float(input("Children= "))
sex_male_input = int(input("Male or Female 0 or 1: "))
smoker_input = int(input("Smoker yes or no 0 or 1: "))

Age=  45
BMI=  66
Children=  1
Male or Female 0 or 1:  1
Smoker yes or no 0 or 1:  1

In [50]:
Future_Predictions = grid.predict([[age_input, bmi_input, children_input, sex_male_input, smoker_input]])

In [52]:
print("Future Predictions = {}".format(Future_Predictions))

Future Predictions = [44783.6242163]