In [16]:
#importing pandas library for accessing database and reading the csv file, also assigning the library to a variable 'pd' for easiness in coding

In [8]:
import pandas as pd

In [6]:
#Using the read_csv function in pandas/pd library to read the csv file and assigning it to a variable 'dataset'

In [9]:
dataset = pd.read_csv("Salary_Data.csv")

In [10]:
dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [17]:
#by using the variable 'dataset', viewing the data in the csv file above

In [12]:
#Assigning independent variable to the input 'YearsExperience'

In [13]:
independent = dataset[["YearsExperience"]]

In [14]:
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [20]:
#viewing the input YearsExperience using the independent variable above

In [31]:
dependent= dataset[["Salary"]]

In [73]:
#Assigning output 'Salary' to the variable 'dependent' above

In [32]:
dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [74]:
#Viewing the output 'Salary' using the variable 'dependent' above

In [75]:
#Splitting the Training dataset and Test dataset below importing the library sklearn of ML; package model_selection and function train_test_split

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
#Assigning training input, output, test input and output values to four variables x_train, x_test, y_train and y_test

In [33]:
x_train, x_test, y_train, y_test = train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [34]:
#Model creation - Learning PhaseI

In [35]:
#using sklearn library, linear_model package, linear regression class creating model below

In [37]:
from sklearn.linear_model import LinearRegression

In [38]:
#Assigning LinearRegression class functions to variable 'regressor'

In [39]:
regressor = LinearRegression()

In [40]:
#creating the model using fit method of LinearRegression passing training dataset; x_train and y_train

In [41]:
regressor.fit(x_train,y_train)

LinearRegression()

In [48]:
#Finding 'weight' and 'bais' and viewing them by calling the associated variables

In [49]:
weight = regressor.coef_

In [50]:
weight

array([[9360.26128619]])

In [51]:
bais=regressor.intercept_

In [52]:
bais

array([26777.3913412])

In [76]:
#Model prediction using test input and predict method of regressor

In [54]:
y_pred=regressor.predict(x_test)

In [57]:
#Evaluation Metrics to evaluate the correctness of the Model using RSquare function from metrics package and sklearn library

In [58]:
from sklearn.metrics import r2_score

In [60]:
#Assigning RSquare function to variable r_score, passing actual output and predicted output as parameters to r2_score function

In [62]:
r_score=r2_score(y_test, y_pred)

In [63]:
#Viewing the r_score

In [64]:
r_score

0.9740993407213511

In [65]:
#Since the r_score is close to 1, the model is good and can be saved

In [66]:
#Importing pickle package for saving the model

In [67]:
import pickle

In [68]:
#Assigning a file name for the model

In [69]:
filename = "finalized_model_linear.sav"

In [71]:
#saving the model against the file; using dump function and passing regressor;writing the model in the file created

In [72]:
pickle.dump(regressor, open(filename, 'wb'))