In [1]:
import matplotlib.pyplot as plt

In [2]:
import pandas as pd

In [3]:
import warnings

In [4]:
warnings.filterwarnings("ignore")

In [5]:
dataset = pd.read_csv("insurance_pre.csv")

In [6]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [7]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [8]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [9]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [10]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [11]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [12]:
dependent = dataset[['charges']]

In [13]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train, x_test, y_train, y_test = train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [16]:
x_train

      age     bmi  children  sex_male  smoker_yes
1163   18  28.215         0         0           0
196    39  32.800         0         0           0
438    52  46.750         5         0           0
183    44  26.410         0         0           0
1298   33  27.455         2         1           0
...   ...     ...       ...       ...         ...
763    27  26.030         0         1           0
835    42  35.970         2         1           0
1216   40  25.080         0         1           0
559    19  35.530         0         1           0
684    33  18.500         1         0           0

[936 rows x 5 columns]

In [17]:
y_train

          charges
1163   2200.83085
196    5649.71500
438   12592.53450
183    7419.47790
1298   5261.46945
...           ...
763    3070.80870
835    7160.33030
1216   5415.66120
559    1646.42970
684    4766.02200

[936 rows x 1 columns]

In [18]:
x_test

      age     bmi  children  sex_male  smoker_yes
578    52  30.200         1         1           0
610    47  29.370         1         0           0
569    48  40.565         2         1           1
1034   61  38.380         0         1           0
198    51  18.050         0         0           0
...   ...     ...       ...       ...         ...
1261   28  37.100         1         1           0
494    21  25.700         4         1           1
97     55  38.280         0         1           0
418    64  39.160         1         1           0
920    62  25.000         0         0           0

[402 rows x 5 columns]

In [19]:
y_test

          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

In [20]:
#Model Creation code for DecisionTreeDT

In [30]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [31]:
from sklearn.model_selection import GridSearchCV

In [32]:
from sklearn.tree import DecisionTreeRegressor

In [35]:
param_grid = {'criterion':['squared_error','absolute_error','poisson'],'max_features':['auto','sqrt','log2'],'splitter':['best','random']}

In [36]:
grid = GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True, verbose = 3, n_jobs=-1)

In [37]:
grid.fit(x_train,y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [38]:
re = grid.cv_results_

In [50]:
grid_predictions = grid.predict(x_test)

In [51]:
#regressor = DecisionTreeRegressor(criterion='friedman_mse',splitter='random',max_features='log2')DT

In [52]:
#regressor = regressor.fit(x_train,y_train)DT

In [53]:
#Code to see how the tree is plottedDT

In [54]:
#import matplotlib.pyplot as pltDT

In [55]:
#from sklearn import treeDT

In [56]:
#tree.plot_tree(regressor)DT

In [57]:
#plt.show()DT

In [58]:
#y_pred = regressor.predict(x_test)DT

In [59]:
#Evaluation Metrics

In [60]:
from sklearn.metrics import r2_score

In [61]:
r_score = r2_score(y_test, grid_predictions)

In [62]:
r_score

0.7691931591160324

In [63]:
print("The R_Score value for the best parameter {}:".format(grid.best_params_),r_score)

The R_Score value for the best parameter {'criterion': 'absolute_error', 'max_features': 'sqrt', 'splitter': 'random'}: 0.7691931591160324

In [64]:
table = pd.DataFrame.from_dict(re)

In [65]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002463,0.001052,0.000000,0.000000,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
1,0.002645,0.000963,0.000000,0.000000,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
2,0.009633,0.002348,0.004440,0.001004,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.730591,0.612289,0.698619,0.541645,0.667583,0.650145,0.066829,3
3,0.007366,0.001672,0.004108,0.000956,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.502112,0.602519,0.615892,0.453162,0.526526,0.540042,0.061361,12
4,0.008442,0.000904,0.004419,0.000961,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.668229,0.570852,0.678390,0.557576,0.693302,0.633670,0.057422,7
5,0.007195,0.000759,0.004607,0.001136,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.710606,0.548273,0.511231,0.535332,0.542391,0.569567,0.071637,11
6,0.001806,0.000637,0.000000,0.000000,absolute_error,auto,best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
7,0.001024,0.000218,0.000000,0.000000,absolute_error,auto,random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
8,0.021272,0.003004,0.003542,0.001128,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.748252,0.588396,0.551924,0.552028,0.660719,0.620264,0.075312,8
9,0.016966,0.002582,0.003576,0.000619,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.786021,0.622885,0.695677,0.638292,0.666838,0.681943,0.057693,1
10,0.022193,0.001951,0.003176,0.000929,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.666511,0.687528,0.695395,0.679455,0.609503,0.667678,0.030616,2
11,0.015006,0.002067,0.002699,0.000246,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.635918,0.650111,0.662619,0.633197,0.626097,0.641588,0.013096,5
12,0.000818,0.000142,0.000000,0.000000,poisson,auto,best,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.000817,0.000092,0.000000,0.000000,poisson,auto,random,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
14,0.006330,0.001191,0.002328,0.000426,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.731659,0.567026,0.740981,0.603318,0.568266,0.642250,0.077961,4
15,0.004720,0.000805,0.002904,0.000217,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.672476,0.604824,0.598437,0.404021,0.604602,0.576872,0.090590,10
16,0.005471,0.000366,0.002800,0.000606,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.708304,0.650023,0.654872,0.622676,0.566672,0.640509,0.046180,6
17,0.003878,0.000421,0.002498,0.000485,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.688390,0.589617,0.540530,0.585336,0.594716,0.599718,0.048373,9

In [66]:
age_input = float(input("Age= "))
bmi_input = float(input("Bmi= "))
children_input = float(input("Children= "))
sex_male_input = int(input("Sex Male or not 0 or 1= "))
smoker_yes_input = int(input("Smoker yes or no= "))

Age=  36
Bmi=  71
Children=  3
Sex Male or not 0 or 1=  1
Smoker yes or no=  1

In [68]:
Future_predictions = grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])

In [69]:
print("Future_predictions:{}".format(Future_predictions))

Future_predictions:[15555.18875]